services:
  - type: web
    name: bazzar-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /api/products
    envVars:
      - key: DATABASE_URL
        sync: false          # You will paste this in Render dashboard
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"
